################################################################################################
###                                                                                          ###
###                                         RANKTREE                                         ###
###                                       Version 1.0.0                                      ###
###                                                                                          ###
################################################################################################

# The following sections build the locations for 3 spawns which the player will be teleported to
# upon selecting their path. Please note that the world is the name of a world as a string surrounded by "".
# As well, any coordinate (x, y, z, pitch, or yaw) not set will default to 0 so it is important to make sure
# there are set before your players are teleported to a random location

# Roman Spawn
roman-spawn:
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0
  world: "world"

# Greek Spawn
greek-spawn:
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0
  world: "world"

# Japanese Spawn
japanese-spawn:
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0
  world: "world"
