name: RankTree
version: '${project.version}'
main: org.infamousmc.ranktree.Main
api-version: 1.18
authors: [ devJordan ]
description: Private Infamous plugin.
softdepend:
  - HeadDatabase
  - LuckPerms
  - Vault

commands:
  Ranktree:
  Rankup:
  Rankpath:
    aliases: [path]
  Ranks:
  Test: